### ISSUE TITLE
Error occurs when parent modules are previously imported

### ISSUE THREAD

**Issue by spacebuoy** [mnmelo/lazy_import#2]
This first occurred in my modules but the error also occurs with python email module.  The error occurs when email is system imported before lazy_module('email.mime') or lazy_module('email.mime.audio') or email.mime is imported before lazy_module('email.mime.audio'). 

Ceti$ py
Python 3.6.4 (v3.6.4:d48ecebad5, Dec 18 2017, 21:07:28) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from  lazy_import import lazy_module
>>> import sys
>>> 'email' in sys.modules
False
>>> lazy_module('email.mime.audio')  # This works
>>> ^D

Ceti$ py
Python 3.6.4 (v3.6.4:d48ecebad5, Dec 18 2017, 21:07:28) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from  lazy_import import lazy_module
>>> import email
>>> import sys
>>> 'email' in sys.modules
True
>>> lazy_module('email.mime.audio')  # This fails first time, works on second call
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/lazy_import/__init__.py", line 302, in lazy_module
    mod = _lazy_module(modname, error_strings, lazy_mod_class)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/lazy_import/__init__.py", line 354, in _lazy_module
    super(LazyModule, mod).__setattr__(submodname, submod)
TypeError: super(type, obj): obj must be an instance or subtype of type
>>>

**Comment by mnmelo** [comment]
Confirmed this was creeping up when lazy-loading submodules of fully-loaded base modules. Fix was simple, but since this has serious impact I released v0.2.2 with it right away.

**Comment by spacebuoy** [comment]
Fixed! Great to get the quick turnaround. All is working well.

**Comment by spacebuoy** [comment]
I think I'm following the directions but I am encountering an error with this command
obj = lazy_callable('cmd.Cmd')
Adding "import cmd" before the above command avoids the error.
Does the cmd module need to be imported beforehand?

**Comment by mnmelo** [comment]
Could you open a new issue with the question, and the exact lines you're using? On a first check I can run that without problems.
